import { ADDITIONAL_FIELDS, ADDITIONAL_GUIDES, ADDITIONAL_PROGRAMS, TOPICS } from "./expanded-content.js";
import { NEW_PROGRAMS } from "./inventory-expansion.js";
import { VARIETY_PROGRAMS } from "./variety-expansion.js";
import { ORGANIC_EXPANSION_PROGRAMS } from "./organic-expansion.js";
import { CONTENT_EXPANSION_2_PROGRAMS } from "./content-expansion-2.js";
import { CONTENT_EXPANSION_3_PROGRAMS } from "./content-expansion-3.js";
import { CONTENT_EXPANSION_4_PROGRAMS } from "./content-expansion-4.js";
import { GUIDE_EXPANSION } from "./guide-expansion.js";
export { TOPICS } from "./expanded-content.js";
export const SITE = "https://firstinternships.com";
export const VERIFIED = "2026-09-19";
export const CONTACT = "contactfirstinternships@gmail.com";
const source = (name, url) => ({ name, url });
const PROGRAM_SEO = {
  "microsoft-explore": ["Microsoft Explore Internship: How to Apply", "Learn who can apply to Microsoft Explore, how the first- and second-year program works, and how to prepare before using the official careers portal."],
  "nasa-ostem": ["NASA OSTEM Internships: Eligibility & Application", "Check NASA OSTEM college eligibility, GPA and citizenship rules, the published Summer 2027 deadline, and practical steps to apply through NASA."],
  "nasa-pathways": ["NASA Pathways Internships: How to Apply", "Understand NASA Pathways college credits, GPA, enrollment and 480-hour requirements before following the official USAJOBS application route."],
  "doe-suli": ["DOE SULI Internship: Requirements & Application", "Check SULI college coursework and GPA requirements, Spring 2027 dates, stipend details, transcripts, references, and the official application route."],
  "doe-cci": ["DOE CCI Internship: How to Apply", "Explore DOE CCI for community-college students: coursework, GPA and enrollment rules, Spring 2027 dates, and the official application checklist."],
  "nsf-reu": ["NSF REU Programs: Eligibility & How to Apply", "Learn how NSF REU site applications work, check undergraduate eligibility, compare research interests and funding, and prepare your site-specific materials."],
  "jpl-summer": ["JPL Summer Internship: Requirements & Application", "Review JPL Summer college eligibility, application materials and preparation advice. The last published cycle is closed; check JPL for future dates."],
  "goldman-sachs-summer-analyst": ["Goldman Sachs Summer Analyst 2027: How to Apply", "Understand Goldman Sachs Summer Analyst 2027, usual penultimate-year timing, business selection, and how to check current official applications."],
  "ey-internships": ["EY Internships: Requirements & How to Apply", "Choose an EY US undergraduate internship service line, check role-specific degree and graduation rules, and prepare for the official application."],
  "deloitte-internships": ["Deloitte Internships: Requirements & Application", "Find the current Deloitte US undergraduate internship route, check track and office qualifications, and prepare an application without guessing class-year rules."],
};

// Program directories, not individual job offers. Null eligibility means we
// cannot infer a minimum class year from the publisher's current program page.
export const PROGRAMS = [
  {
    id: "microsoft-explore", company: "Microsoft", title: "Explore Microsoft", initials: "MS", color: "#2876b9",
    fields: ["technology"], firstYear: 1, years: [1, 2], yearLabel: "Years 1–2", pay: "Paid", location: "US & India; check opening", mode: "Role-specific",
    summary: "A software-development introduction specifically designed for students in their first two college years.",
    eligibility: ["Designed for first- and/or second-year college students interested in a technical discipline.", "The US program is 12 weeks; the India program is 8 weeks.", "Country, enrollment, and work-authorization requirements must be checked in the individual opening."],
    timing: "Summer program. A specific Explore application window is not confirmed here; check the current careers listings.", status: "Check openings",
    url: "https://careers.microsoft.com/v2/global/en/exploremicrosoft",
    sources: [source("Explore Microsoft overview", "https://careers.microsoft.com/v2/global/en/exploremicrosoft"), source("University internship pay and hiring guidance", "https://careers.microsoft.com/v2/global/en/universityinternship")],
    steps: ["Find an Explore opening for your country on Microsoft Careers, rather than applying to an unrelated role displayed on the overview page.", "Read its required qualifications and graduation/enrollment rules. Put your expected graduation month and year on your resume.", "Submit through the official careers portal and use its Action Center to track the employer's decision."],
    prepare: ["Use one class or personal software project to show how you approach a problem. Explain the user, your contribution, the technology you chose, and one trade-off. A small working project is easier to discuss than a long list of tools you have barely used.", "Practice describing how you debugged a failure and how you worked with someone else. Our suggestion is to make your learning process visible; this is not a promise about Microsoft's interview questions."],
    pitfall: "Explore's first/second-year focus is not a minimum followed by automatic eligibility for juniors and seniors.",
    materials: ["Resume with graduation date", "Opening-specific eligibility check", "Project examples", "Official portal confirmation"],
  },
  {
    id: "nasa-ostem", company: "NASA", title: "NASA OSTEM Internships", initials: "NA", color: "#173d8e",
    fields: ["engineering", "research", "technology", "business", "aerospace"], firstYear: 1, years: [1, 2, 3, 4], yearLabel: "Undergraduate years 1–4", pay: "Paid", location: "NASA centers; check project", mode: "Project-specific",
    summary: "Project-based college internships across STEM and non-STEM work at NASA.",
    eligibility: ["Current college students may be enrolled full time or part time in a degree-granting program at an accredited institution.", "US citizenship, a cumulative 3.0 GPA, and a minimum age of 16 are program-level requirements.", "A project's skills, education level, and other qualifications still apply. This directory covers the college route only."],
    timing: "NASA lists February 26, 2027 at 11:59 p.m. ET as the Summer 2027 deadline. Summer internships last 10 weeks; spring/fall terms last 15 weeks.", status: "Published deadline", deadline: "2027-02-27T04:59:00Z", deadlineZone: "America/New_York", deadlineLabel: "Summer 2027 · Feb 26, 11:59 p.m. ET",
    url: "https://www.nasa.gov/learning-resources/internship-programs/",
    sources: [source("NASA internship programs and dates", "https://www.nasa.gov/learning-resources/internship-programs/"), source("NASA internship eligibility FAQ", "https://www.nasa.gov/learning-resources/internship-programs/intern-frequently-asked-questions/")],
    steps: ["Choose OSTEM on NASA's official internship page and follow the current application link.", "Read each project carefully and match it to coursework, tools, or interests you can demonstrate. Check that the project accepts undergraduates.", "Complete the employer's requested application materials and submit before the term deadline. Keep the project identifier and confirmation in your own records."],
    prepare: ["Start with the project, not the NASA name. For a data project, describe a dataset you cleaned and the conclusion you reached. For communications or business work, show a writing sample, campus organization project, or process you improved.", "A first-year applicant can use laboratory coursework or a small independent project honestly. Identify what you already know and what you would need to learn; do not claim experience with equipment or methods you have only read about."],
    pitfall: "OSTEM and Pathways have different rules and application processes. Eligibility for one does not establish eligibility for the other.",
    materials: ["Project qualification review", "Resume and education details", "Required academic records", "Term availability"],
  },
  {
    id: "nasa-pathways", company: "NASA", title: "NASA Pathways Internships", initials: "NP", color: "#253a67",
    fields: ["engineering", "technology", "business", "aerospace"], firstYear: 1, years: [1, 2, 3, 4], yearLabel: "Year 1+ · credits & time required", pay: "Paid", location: "See USAJOBS announcement", mode: "Role-specific",
    summary: "A paid federal student employment pathway with coursework and remaining-work-time requirements.",
    eligibility: ["US citizenship, at least half-time enrollment, and a cumulative GPA of at least 2.9 are required.", "Complete at least 15 semester or 23 quarter credit hours.", "You must be able to work at least 480 hours before completing your degree. Seniors need to check this carefully.", "The individual federal announcement controls the full requirements and selection process."],
    timing: "Applications follow individual USAJOBS announcements. No universal opening or closing date is asserted here.", status: "Check announcements",
    url: "https://www.nasa.gov/learning-resources/internship-programs/",
    sources: [source("NASA Pathways requirements", "https://www.nasa.gov/learning-resources/internship-programs/")],
    steps: ["Follow NASA's official Pathways link to current USAJOBS student announcements.", "Check the announcement's education, documents, work schedule, location, and closing time. Calculate whether the required hours fit before graduation.", "Use the resume and document instructions in that announcement, complete its questionnaires, and submit through USAJOBS."],
    prepare: ["Treat the federal announcement as a checklist. Map every requirement to a document or a concrete example before drafting. The resume format and detail requested may differ from a private-company campus resume; follow the current announcement rather than a generic template.", "Plan the work schedule with your academic adviser. Semester availability, travel, and graduation timing can determine whether this is workable even when your class year and GPA fit."],
    pitfall: "Potential conversion to federal employment is not a guaranteed full-time offer.",
    materials: ["USAJOBS announcement review", "Required resume format", "Enrollment and transcript documents", "480-hour feasibility check"],
  },
  {
    id: "doe-suli", company: "US Department of Energy", title: "Science Undergraduate Laboratory Internships (SULI)", initials: "DE", color: "#387448",
    fields: ["research", "engineering", "technology"], firstYear: 1, years: [1, 2, 3, 4], yearLabel: "Year 1+ · after one semester", pay: "Paid", location: "US national laboratories", mode: "On-site",
    summary: "Research with a scientist or engineer at a participating national laboratory; eligible first-years need completed college coursework.",
    eligibility: ["For the current-student route: full-time undergraduate enrollment, one completed matriculated semester, 12 total undergraduate credits, and 6 STEM credits by the deadline.", "A cumulative 3.0 GPA, US citizenship or lawful permanent residency at application, and age 18 by the start are required.", "Pre-college/AP credits do not replace the completed-semester or minimum-credit requirements."],
    timing: "Spring 2027 applications are due September 30, 2026 at 5 p.m. ET. The published benefits include a $650 weekly stipend; summer terms are typically 10 weeks and semester terms 16 weeks.", status: "Published deadline", deadline: "2026-09-30T21:00:00Z", deadlineZone: "America/New_York", deadlineLabel: "Spring 2027 · Sep 30, 5 p.m. ET",
    url: "https://science.osti.gov/wdts/suli/How-to-Apply",
    sources: [source("SULI eligibility", "https://science.osti.gov/wdts/suli/Eligibility"), source("Application instructions and deadline", "https://science.osti.gov/wdts/suli/How-to-Apply"), source("Stipend and on-site participation", "https://science.osti.gov/wdts/suli/Benefits")],
    steps: ["Choose laboratory interests and complete the official online application, including its essays.", "Upload the required undergraduate transcripts. DOE requires removal of Social Security numbers and full dates of birth; transcript screenshots and degree audits are not accepted.", "Arrange two letters of support using the current system. Review all sections and submit a complete application before the deadline."],
    prepare: ["Read about a laboratory's current research before explaining your interest. Connect a course, experiment, or coding exercise to a specific question you want to investigate. You do not need to pretend your class project was professional research.", "Give potential recommenders time and context: your resume, why the lab work interests you, the deadline, and a reminder of work they supervised. Track the letters separately from your own application submission."],
    pitfall: "Being in year one is not enough: the completed-semester and credit rules must already be satisfied by the application deadline.",
    materials: ["Credit and GPA check", "Redacted transcript PDFs", "Two letters of support", "Research-interest essays"],
  },
  {
    id: "doe-cci", company: "US Department of Energy", title: "Community College Internships (CCI)", initials: "CC", color: "#548a36",
    fields: ["engineering", "research", "technology"], firstYear: 1, years: [1, 2, 3, 4], yearLabel: "Community / two-year college", pay: "Paid", location: "US national laboratories", mode: "See host requirements",
    summary: "Technical laboratory experience for students enrolled at community colleges and accredited two-year colleges.",
    eligibility: ["Full- or part-time enrollment at a community college or accredited two-year college, plus one completed matriculated semester.", "At least 12 total undergraduate credits, 6 STEM credits, and a cumulative GPA of 2.7. A GPA below 3.0 requires a waiver statement.", "US citizenship or lawful permanent residency at application; age 18 by the internship start.", "Pre-college credits do not replace the minimum coursework requirement."],
    timing: "Spring 2027 applications are due September 30, 2026 at 5 p.m. ET. CCI describes paid 10-week experiences.", status: "Published deadline", deadline: "2026-09-30T21:00:00Z", deadlineZone: "America/New_York", deadlineLabel: "Spring 2027 · Sep 30, 5 p.m. ET",
    url: "https://science.osti.gov/wdts/cci",
    sources: [source("CCI program, pay and deadline", "https://science.osti.gov/wdts/cci"), source("CCI eligibility and GPA waiver", "https://science.osti.gov/wdts/cci/Eligibility")],
    steps: ["Use the official CCI page to find the current application system and checklist.", "Review the technical areas at participating laboratories, then choose interests that match your coursework.", "Prepare the transcripts, recommendations, essays, and any GPA waiver requested by the current checklist. Verify completeness before submitting."],
    prepare: ["A technical course can provide a useful example: a measurement you took, a part you designed, code you tested, or a safety procedure you followed. Explain your contribution and how you checked the result.", "Talk to a faculty member about which laboratory areas match your training. If transferring to a four-year institution, confirm that your enrollment situation still meets CCI's rules for the term instead of assuming the opportunity transfers with you."],
    pitfall: "CCI is not a generic four-year-college internship. Enrollment type matters as much as class year.",
    materials: ["Community-college enrollment check", "Completed coursework review", "Current application checklist", "GPA waiver if required"],
  },
  {
    id: "nsf-reu", company: "NSF-funded research sites", title: "Research Experiences for Undergraduates (REU)", initials: "NS", color: "#4564a5",
    fields: ["research", "engineering", "technology"], firstYear: 1, years: [1, 2, 3, 4], yearLabel: "Undergraduates · site-specific", pay: "Paid", location: "Participating research sites", mode: "Site-specific",
    summary: "Funded undergraduate research opportunities offered by individual universities and research organizations, not one centralized internship.",
    eligibility: ["NSF-funded REU participants must be undergraduate students pursuing an associate or bachelor's degree and US citizens, US nationals, or permanent residents.", "Individual sites can set additional coursework, class-year, or other eligibility criteria.", "There is no blanket rule that all REU sites accept first-years or graduating seniors."],
    timing: "Dates vary by site. NSF says participants receive stipends and many sites provide help with housing, meals, or travel; confirm each site's package.", status: "Site-specific dates",
    url: "https://www.nsf.gov/funding/initiatives/reu/students",
    sources: [source("NSF REU student eligibility and site directory", "https://www.nsf.gov/funding/initiatives/reu/students"), source("NSF undergraduate application overview", "https://www.nsf.gov/funding/undergraduates")],
    steps: ["Find sites in NSF's REU directory or ETAP. Not every site uses ETAP, so follow each site's own application instructions.", "Check the site's specific eligibility, research themes, dates, stipend, and housing arrangements.", "Submit the site's requested materials, which may include a statement of interest, academic records, and references. Track each deadline separately."],
    prepare: ["Build a short comparison of research questions, not just university names. Read the site description and identify which methods you have used in class and which you hope to learn. Explain why that particular research setting fits your next step.", "For your statement, describe a question that caught your attention and what you did to explore it. Our advice is to use an honest, specific example rather than broad claims about loving science since childhood."],
    pitfall: "NSF does not collect one universal application for all REUs. Site requirements and student-status rules differ.",
    materials: ["Site eligibility and dates", "Research statement", "Site-requested academic records", "References if requested"],
  },
  {
    id: "jpl-summer", company: "NASA Jet Propulsion Laboratory", title: "JPL Summer Internship Program", initials: "JP", color: "#b85030",
    fields: ["research", "engineering", "technology", "aerospace"], firstYear: 1, years: [1, 2, 3, 4], yearLabel: "Undergraduates · STEM", pay: "Paid", location: "JPL · Pasadena, California", mode: "Check program arrangements",
    summary: "A 10-week, full-time STEM internship at JPL. The last published summer deadline has passed; use this guide to prepare for a future cycle.",
    eligibility: ["The program accepts undergraduate and graduate STEM students at accredited US universities.", "A 3.0 GPA at the current active institution and US citizenship or lawful permanent residency are required.", "No college class-year minimum is stated on the program page; project and enrollment rules still matter."],
    timing: "The last published deadline was March 13, 2026 at 5 p.m. PDT, which has passed. A new cycle is not confirmed here. JPL describes 10 weeks at 40 hours per week and a variable monthly monetary award.", status: "Last cycle closed", deadline: "2026-03-14T00:00:00Z", deadlineZone: "America/Los_Angeles", deadlineLabel: "Summer 2026 · Mar 13, 5 p.m. PDT",
    url: "https://www.jpl.nasa.gov/edu/internships/apply/jpl-summer-internship-program/",
    sources: [source("JPL summer requirements, materials and published deadline", "https://www.jpl.nasa.gov/edu/internships/apply/jpl-summer-internship-program/"), source("JPL internship FAQ", "https://www.jpl.nasa.gov/edu/internships/faq/")],
    steps: ["Check the official program page for a new application cycle before starting an application.", "Prepare the resume and unofficial transcript identified by the program, and follow the official application-system link.", "Describe relevant research interests and availability. Mentors may interview candidates before selecting them; an application is not an offer."],
    prepare: ["Connect your experience to a technical problem: controls, robotics, sensing, software, materials, or another relevant area. Describe what you measured or built, what failed, and how you verified an improvement.", "Plan the practical side alongside the application. Ask about the actual work arrangement, relocation costs, and award details before accepting. Do not assume housing is automatically provided or that you can participate remotely."],
    pitfall: "An evergreen program page is not proof that a current internship is open. This record intentionally shows the passed deadline.",
    materials: ["New-cycle confirmation", "Resume", "Unofficial transcript", "Full-time summer availability"],
  },
  {
    id: "goldman-sachs-summer-analyst", company: "Goldman Sachs", title: "2027 Summer Analyst Program", initials: "GS", color: "#5681a0",
    fields: ["finance", "business"], firstYear: null, years: [], preferredYears: [3], yearLabel: "Usually year 3 / penultimate", pay: "Check opening", location: "Americas · opening-specific", mode: "Role-specific",
    summary: "A nine- to ten-week undergraduate summer program, usually undertaken during the third or penultimate year of study.",
    eligibility: ["Candidates are currently pursuing a college or university degree.", "Goldman describes third or penultimate year as the usual timing, not a universal minimum-year rule.", "Business, location, and graduation-date requirements must be confirmed in the selected application."],
    timing: "Summer 2027. The program page says applications for select businesses are open; verify availability for the business and location you select.", status: "Select businesses listed open",
    url: "https://www.goldmansachs.com/careers/students/programs-and-internships/americas/2027-summer-analyst-program",
    sources: [source("Goldman Sachs 2027 Summer Analyst overview", "https://www.goldmansachs.com/careers/students/programs-and-internships/americas/2027-summer-analyst-program")],
    steps: ["Use the program's official Apply Now link to see available businesses and locations.", "Read the exact application's degree and graduation-date criteria. Choose a business because its work fits your interests, not solely because of its brand.", "Tailor your resume to that business and submit through the official student application portal. Follow any assessment instructions you receive."],
    prepare: ["Be able to explain what your chosen business does and why it fits your interests. For an analytical team, a coursework model, investment write-up, or data exercise can show how you reason; label academic and simulated work clearly.", "Prepare a concise discussion of a current business question you understand. Explain the assumptions and uncertainty rather than memorizing a confident prediction. This is editorial preparation advice, not a statement of Goldman's interview format."],
    pitfall: "A four-year junior and a penultimate-year student on a different degree timeline may not have the same graduation date. Read the actual opening.",
    materials: ["Business and location selection", "Graduation-date check", "Tailored resume", "Portal and assessment tracking"],
  },
  {
    id: "ey-internships", company: "EY US", title: "EY College Internships", initials: "EY", color: "#75621c",
    fields: ["business", "finance", "consulting"], firstYear: null, years: [], yearLabel: "Year depends on opening", pay: "Check opening", location: "US · office-specific", mode: "Role-specific",
    summary: "Summer and winter internship routes; use the individual listing to confirm service line, degree, and graduation criteria.",
    eligibility: ["EY's overview includes undergraduate and graduate internship routes. We cover undergraduate applications here.", "A universal minimum class year is not stated on the overview page.", "An assurance, tax, consulting, or other opening may have specific degree, coursework, professional-qualification, and graduation requirements."],
    timing: "EY says summer applications are generally available in the preceding fall and reviewed on a rolling basis. Availability and dates remain role-specific.", status: "Check openings",
    url: "https://www.ey.com/en_us/careers/internships-student-programs",
    sources: [source("EY internships and student programs", "https://www.ey.com/en_us/careers/internships-student-programs"), source("EY application timing FAQ", "https://www.ey.com/en_us/careers/frequently-asked-questions")],
    steps: ["Start on EY's official student-program page and follow the current US opening links.", "Choose a service line and office, then review the exact degree, coursework, and graduation requirements. Check any CPA-related education requirements if relevant.", "Submit the requested resume and information through the official recruiting site. Keep a copy of the listing and any assessment invitation."],
    prepare: ["Make your reason for choosing the service line concrete. An accounting course, student organization's budget, analytics exercise, or client-facing campus job can provide a grounded example of relevant work.", "Before selecting an office, confirm your ability to work there for the full term. Use your campus career center for application review, but do not mistake a campus event or informational conversation for an official application."],
    pitfall: "Do not treat all EY internships as having identical eligibility or assume a first-year program exists because a previous cycle had one.",
    materials: ["Specific role eligibility", "Service line and office choice", "Resume", "Academic/professional qualification review"],
  },
  {
    id: "deloitte-internships", company: "Deloitte US", title: "Deloitte College Internships", initials: "DL", color: "#4d6c24",
    fields: ["business", "finance", "technology", "consulting"], firstYear: null, years: [], yearLabel: "Year depends on opening", pay: "Check opening", location: "US · office-specific", mode: "Role-specific",
    summary: "Student internship opportunities across different teams. Confirm the current track and requirements before applying.",
    eligibility: ["Use an individual undergraduate internship opening to establish eligibility.", "Deloitte's current general internship page does not establish one minimum college year for every track.", "Service line, office, coursework, graduation date, and authorization criteria can differ. Past Discovery descriptions should not be substituted for a current opening."],
    timing: "Recruiting windows and availability depend on the current opening; no universal deadline is stated here.", status: "Check openings",
    url: "https://www.deloitte.com/us/en/careers/internships.html",
    sources: [source("Deloitte US current internship directory", "https://www.deloitte.com/us/en/careers/internships.html"), source("Deloitte US student careers", "https://www.deloitte.com/us/en/careers/student-careers.html")],
    steps: ["Follow View Open Roles from the official internship page and locate a student internship relevant to your degree.", "Read the track and office's required qualifications. Verify the posting is for the term you want, not an expired prior-year cycle.", "Complete the official application and requested assessments. Record the role identifier so you can distinguish multiple applications."],
    prepare: ["Translate a project into the team's work. Explain a problem, your analysis, what you recommended, and the evidence supporting it. For a technical team, show the implementation as well as the presentation.", "Prepare examples of collaborating through an ambiguous task. Be precise about which part you owned and how the group made a decision. Our advice is to demonstrate judgment, not to recite a generic consulting script."],
    pitfall: "An old Discovery program article does not establish eligibility for a newly posted Discovery or client-service internship.",
    materials: ["Current role and term", "Track-specific qualifications", "Resume", "Role identifier and confirmation"],
  },
  ...ADDITIONAL_PROGRAMS,
  ...NEW_PROGRAMS,
  ...VARIETY_PROGRAMS,
  ...ORGANIC_EXPANSION_PROGRAMS,
  ...CONTENT_EXPANSION_2_PROGRAMS,
  ...CONTENT_EXPANSION_3_PROGRAMS,
  ...CONTENT_EXPANSION_4_PROGRAMS,
].map(program => ({ ...program, verified: program.verified || VERIFIED, seoTitle: program.seoTitle || PROGRAM_SEO[program.id][0], seoDescription: program.seoDescription || PROGRAM_SEO[program.id][1] }));

export const YEARS = [
  { id: 1, slug: "freshman-internships", name: "First-year", short: "1st year", color: "#d9f99d", title: "Internships for First-Year College Students", description: "Find freshman internship pathways, check completed-credit rules, and build an application from coursework and projects.",
    intro: "You do not need to wait until junior year to start looking. Begin with programs that explicitly accept early-college students, then check any coursework or enrollment conditions before spending time on an application.",
    sections: [["Start with evidence, not a long work history", "A lab report, small app, campus job, club event, or volunteer project can explain what you can do. Write down the task, your contribution, and the result. Never rename a class exercise as a professional internship."], ["Year one is not the whole eligibility test", "Explore Microsoft focuses on the first two college years. DOE programs require a completed semester and specific credits, so a student in their first fall semester may not yet qualify. Research sites can set their own additional rules."], ["Make a manageable first shortlist", "Choose opportunities whose dates, location, citizenship rules, and costs fit your situation. Use campus research and career resources alongside these national programs. Save a few realistic choices and finish the strongest applications first."]],
  },
  { id: 2, slug: "sophomore-internships", name: "Sophomore", short: "2nd year", color: "#c9e9ff", title: "Internships for College Sophomores", description: "Compare second-year internship pathways, understand credit and enrollment requirements, and turn coursework into application evidence.",
    intro: "Sophomore year is a useful time to move from exploring fields to testing one in practice. You can still consider early-college programs while adding research and technical opportunities that need completed coursework.",
    sections: [["Do not miss early-college windows", "Programs limited to the first two years are different from programs with a minimum of year two. Explore Microsoft may fit a sophomore; it should not be assumed available again in junior year. Confirm which year the opening uses: application time or internship start."], ["Use a course to demonstrate a skill", "Choose one substantial assignment and improve it before listing it. Test your code, check a model's assumptions, or explain an experiment's limitations. Include a clear description and a link only if the work is appropriate to share."], ["Compare the full commitment", "A semester laboratory appointment can overlap with classes, and an on-site placement may involve travel and housing. Ask your adviser about academic scheduling and compare the practical details before committing."]],
  },
  { id: 3, slug: "junior-internships", name: "Junior", short: "3rd year", color: "#ffd8c8", title: "Internships for College Juniors", description: "Find junior and penultimate-year internship routes, compare application requirements, and prepare a focused summer application.",
    intro: "Junior year often aligns with penultimate-year summer recruiting on a four-year degree, but graduation dates are more reliable than class labels. Build your shortlist around the actual opening's degree timeline.",
    sections: [["Check the graduation window", "Goldman Sachs describes its Summer Analyst program as usually taken in the third or penultimate year. That is guidance, not a guarantee that every junior qualifies. Accelerated degrees, transfer credits, and co-op schedules can change the fit."], ["Show depth in one relevant area", "Select work that matches the team's tasks. Explain an analytical decision, a tested design, or a substantial project contribution. A focused resume with evidence is easier to evaluate than an unrelated list of every campus activity."], ["Track assessments and term availability", "After applying, check the employer portal and messages for assessments or scheduling requests. Keep copies of the posting and your application. Return offers are possible outcomes of some programs, not a promise made by this directory."]],
  },
  { id: 4, slug: "senior-internships", name: "Senior", short: "4th year", color: "#e4d8ff", title: "Internships for College Seniors", description: "Explore undergraduate internship routes for seniors and check graduation, student-status, and remaining-work-time restrictions.",
    intro: "A senior can still be an undergraduate applicant, but a graduation date can close an internship route before the placement starts. Check student status for both application and participation, not just today's class year.",
    sections: [["Read the enrollment rule literally", "Some openings require another term of study after the internship. Research sites may require undergraduate status throughout participation. A program accepting undergraduates is not automatic confirmation for someone graduating before its start."], ["Calculate remaining time", "NASA Pathways requires the ability to complete at least 480 work hours before finishing your degree. A final-semester applicant needs a real schedule, not just a qualifying GPA. Discuss leave, credit, and graduation timing with your academic adviser."], ["Separate internships from graduate jobs", "This board covers current-college pathways. If a role's timing does not fit, use the employer's graduate recruiting route instead. A full-time graduate opening is not relabeled as a senior internship here."]],
  },
];

export const FIELDS = [
  ...ADDITIONAL_FIELDS,
  { id: "technology", name: "Technology", title: "Technology Internships for College Students", description: "Software, data, and technical internship pathways with college-year eligibility and practical application guidance.", intro: "Choose the work before choosing the company: software development, data analysis, research computing, and technical operations call for different evidence.", sections: [["Build something you can explain", "Show a small working project with a readable description, setup steps, and tests where appropriate. Explain your contribution and a trade-off. Keep private data and course work subject to academic restrictions out of public repositories."], ["Match the technical requirements", "Distinguish required tools from preferred ones in the opening. Identify what you have used, how you used it, and what you would need to learn. An interest in technology is not evidence that you meet a specific advanced role's prerequisites."]] },
  { id: "engineering", name: "Engineering", title: "Engineering Internships for College Students", description: "Compare engineering and laboratory internship programs, completed-credit rules, and preparation advice for undergraduate applicants.", intro: "Engineering experience can begin in a classroom lab or design team. The useful question is what you designed, measured, tested, or improved—and how you know it worked.", sections: [["Explain the verification", "In a project description, name the constraint, the approach, and the test. A prototype that failed can still show sound reasoning if you explain what the result taught you. Do not imply you operated equipment independently if you worked under supervision."], ["Check location and academic scheduling", "Laboratory and hardware work often has an on-site component. DOE SULI explicitly requires on-site participation. Check the actual work arrangement, safety training, dates, and housing support before comparing an award with your living costs."]] },
  { id: "research", name: "Research", title: "Research Internships for Undergraduates", description: "Explore NSF REU, NASA, JPL, and DOE research pathways with eligibility checks, application steps, and source links.", intro: "An undergraduate research application should explain what you want to investigate and why the lab or site is the right setting. It is not just a list of institutions you admire.", sections: [["Read the research themes first", "Find two or three questions in the site's description that genuinely interest you. Connect one to coursework or a project and explain what you hope to learn. You can acknowledge gaps without pretending to be an experienced researcher."], ["Give recommenders useful context", "Ask someone familiar with your work, give them the relevant program description and deadline, and explain why it fits. Keep a separate record of reference requests, since your own submission may not complete the application."]] },
  { id: "finance", name: "Finance & Accounting", title: "Finance and Accounting Internships for College Students", description: "Compare finance and accounting internship pathways, penultimate-year guidance, and role-specific degree requirements.", intro: "Banking, assurance, tax, and corporate finance are different routes. Identify the team's work, degree requirements, and office before building an application.", sections: [["Graduation dates matter more than labels", "A junior on a standard four-year timeline may fit penultimate-year recruiting; a student on an accelerated or extended degree may not. Check the selected role's expected graduation window, not a generic internet rule about juniors."], ["Use evidence appropriate to the service line", "For finance, explain assumptions in a model or an analytical write-up. For accounting, connect coursework and any relevant education plans to the opening. Clearly label simulated work and do not offer invented returns or exaggerated client responsibilities."]] },
  { id: "business", name: "Business", title: "Business Internships for College Students", description: "College business internship routes with service-line selection, eligibility checks, and actionable application preparation.", intro: "Business is a broad category, not one job. Operations, consulting, finance, and public-sector administration reward different forms of practical evidence.", sections: [["Translate campus work into relevant skills", "A student organization's budget, an event plan, a customer-facing job, or a process improvement can show useful experience. Explain scope honestly: what you owned, who you worked with, and what changed."], ["Select a team and location deliberately", "Read what the team actually does and confirm you can work in its office for the full term. Use a short explanation of why that work fits your interests; replacing the employer name in a generic paragraph rarely produces a useful application."]] },
];

export const GUIDES = [
  ...GUIDE_EXPANSION,
  ...ADDITIONAL_GUIDES,
  { slug: "how-to-apply-for-an-internship", title: "How to Apply for a College Internship", description: "A practical internship application process: verify eligibility, prepare evidence, submit through the official portal, and track the next step.", intro: "Start by checking whether you can actually participate. A polished application cannot fix an incompatible graduation date, required credit count, citizenship restriction, or work schedule.", sections: [
    ["1. Turn the listing into a checklist", "Before writing anything, copy the essentials out of the posting: employer, role title and identifier, term dates, location and work arrangement, deadline with its time zone, and the required documents. Separate required qualifications from preferred ones — they are not the same test, and many students disqualify themselves over a preferred item. Check whether class year is assessed when you apply or when the internship begins, because those can be different years for the same person. Where a mandatory rule is genuinely unclear, use the employer's published contact route rather than guessing."],
    ["2. Confirm you can actually participate", "This is the step most worth doing early, because no amount of polish fixes an incompatible graduation date, a credit requirement you have not met, a citizenship or authorization restriction, or a term you cannot attend in full. Read the eligibility wording literally and check the conditions that apply during the placement as well as at application — some programs require you to remain enrolled throughout, or to return to study afterward. If something here rules you out, that is useful information gained in ten minutes rather than ten hours."],
    ["3. Pick the evidence for this specific work", "Choose two or three examples from classes, projects, jobs, research, or campus activities that connect to what the role actually involves. For each, be able to state the task, what you personally did, and the outcome. Use accurate numbers only where you measured something. Make the connection to the role visible without copying phrases from the posting into your resume — a reviewer can tell, and it reads as padding rather than fit."],
    ["4. Assemble the documents the way they asked", "Follow the format, page limits, naming conventions, and upload requirements exactly. Export to PDF unless told otherwise and open the exported file to check nothing shifted. Verify your contact details and graduation date. If transcripts or references are required, start those early — they depend on other people and other systems. Write a cover letter when it is requested or when it genuinely adds context the resume cannot; it does not substitute for any required part of the application."],
    ["5. Submit through the official route", "Apply on the employer's own portal, reached from their official page rather than an aggregator link. FirstInternships is an independent guide: we do not accept applications, submit on your behalf, or store your resume. Before submitting, review the uploaded files and answer every required question. Afterward, save the confirmation, the role identifier, and a copy of the posting, because listings are edited and taken down and you will want the original when preparing for an interview."],
    ["6. Track what happens next", "Record the submission date and watch for assessments, interview requests, or additional document requests — several employers set short response windows and route mail that lands in spam. Use your saved list here as a personal planning record; the employer portal remains the authoritative source for your actual status. Then keep going. Applying to a realistic number of well-matched programs, rather than waiting on any single one, is what makes the timeline work in your favor."],
  ] },
  { slug: "internship-resume-with-no-experience", title: "An Internship Resume With No Previous Internship", description: "Use coursework, campus jobs, and projects to build an honest college internship resume with clear evidence and a graduation date.", intro: "No previous internship does not mean no relevant experience. Your task is to make what you have done understandable, without dressing class work up as professional employment.", sections: [
    ["Start with education and one real project", "Lead with your degree, institution, and expected graduation month and year — that last detail decides eligibility for many programs and reviewers look for it immediately. Then choose relevant coursework or, better, one substantial project you can discuss in depth. For a team project, say plainly what you did rather than what the group produced. Include a link only if the work is genuinely shareable, loads without a login, and explains itself to someone arriving cold; a broken or empty link is worse than none."],
    ["Write bullets around an action and a result", "Replace worked on a data project with what you actually did and what it showed. For example: cleaned a course dataset of 4,000 records, compared two forecasting approaches, and documented their error on a held-out sample. That is an illustrative sentence, not something to claim unless it describes your real work. Start each bullet with a verb, keep it to one or two lines, and include a number only where you genuinely measured something — an invented percentage is the easiest thing in the world to probe in an interview."],
    ["Use jobs and campus activities honestly", "Customer service, tutoring, scheduling, event organization, and running a club budget all demonstrate reliability, communication, and ownership, and reviewers know how to read them. Name the role accurately, give its real scope, and describe outcomes you can defend. A shift lead who handled a rota for twelve people has something concrete to say. What does not work is inflating the title, implying you ran something you helped with, or describing a class exercise as professional employment."],
    ["Make it easy to read and easy to verify", "Use clear section headings, consistent dates, and a restrained single-column layout — decorative templates frequently lose text when a portal parses them. Follow the employer's file instructions exactly. Proofread the exported document rather than the editor view, and check dates, spelling, links, and your own contact details; a wrong email address quietly ends an application. Leave out anything sensitive that was not asked for, including government identification numbers, your full address, a photograph, and your date of birth."],
    ["Tailor by selecting, not by inventing", "For each application, move the most relevant evidence higher and cut what distracts from it. Read the posting for the specific skills it names and make sure the matching evidence is visible in the top half of the page. If you do not have something the role requires, do not claim it — a small project you can explain properly is far more persuasive than a list of tools you cannot discuss for sixty seconds. Ask a career adviser or someone in the field to read it before you submit."],
    ["Remember what a resume is for", "It is not a complete record of everything you have done; it is an argument that you are worth a conversation. One page is right for almost every undergraduate applicant. If something does not support that argument for this particular role, it can come out — and it can go back in for a different application. Keep a longer private master document with everything, and cut each submitted version down from it rather than rebuilding from scratch every time."],
  ] },
  { slug: "when-to-apply-for-summer-internships", title: "When to Apply for Summer Internships", description: "Plan college internship applications around official deadlines, rolling recruiting, reference requests, and your academic calendar.", intro: "There is no single deadline for summer internships. Build your calendar from the actual programs and roles you want, then work backward from their requirements.", sections: [
    ["Start watching before you feel ready", "There is no single summer internship deadline, and waiting for one costs people opportunities every year. Build a shortlist during the preceding academic year and start checking official employer pages then. Structured programs at large employers often recruit early — sometimes a full year ahead for finance and technology — while research sites, smaller teams, and public-sector programs run on their own schedules, several of them in late winter or spring. Your documents should be ready before the first window you care about opens, not drafted in a rush once it does."],
    ["Tell a deadline apart from rolling review", "A deadline is a published last submission time, usually with a time zone, and it is the same for everyone. Rolling review means applications are read as they arrive and a program can close when it is full, which makes early submission genuinely worth something. An evergreen overview page describing a program in general terms is evidence of neither: it is not proof that an application is currently open. Work from the individual opening and the current cycle announcement, and treat a page with no stated date as a page to re-check rather than one with time to spare."],
    ["Work backward from your dependencies", "The parts of an application other people control set your real timeline. Transcripts have processing times. Recommenders need weeks, the program description, the deadline, and a reminder — and your submission may not count as complete until their letters arrive. Essays need a draft, a gap, and a second read. List these for each application, then set your own submission target several days before the employer cutoff so a portal problem or a slow upload is an inconvenience rather than a lost application."],
    ["Check the dates against your actual year", "Compare the full internship dates with your exam period, any required classes, commencement, and anything already committed. A placement that starts before your term ends or runs past the start of the next one needs a plan agreed with your academic adviser, not an assumption. Confirm the work arrangement, the location, and any housing or relocation support before accepting rather than after, and remember that a published term length is sometimes negotiable at the edges and sometimes not at all."],
    ["Keep closed programs on a watch list", "A passed deadline usually points at a real opportunity in the next cycle, and the requirements are often stable even when the dates are not. Save the official page, note roughly when the last cycle opened, and set a reminder to check well before that point — but never write next year's date into your calendar as though it were announced. Last year's deadline is a hint about timing, not a fact about this year, and a program can move, change, or pause without notice."],
    ["Put the whole thing on one calendar", "Applications fail on forgetting far more often than on merit. Keep every cutoff, opening date, and personal submission target in one calendar you actually look at, with the time zone written down. Add a reminder a week ahead of each, not the day before, so there is room to fix a problem. This site's deadline hub lists the cutoffs we have verified and can export them, and the timeline builder turns a target date into a workback plan — but your own calendar, checked regularly, is what makes either of them useful."],
  ] },
  { slug: "internship-interview-guide", title: "Prepare for a College Internship Interview", description: "Prepare project explanations, examples of collaboration, employer questions, and practical checks for a college internship interview.", intro: "Preparation means being able to explain your work clearly and understand the role. This guide is general editorial advice; the employer's interview instructions determine the actual format.", sections: [
    ["Build a short evidence bank", "Prepare four or five examples you can use flexibly rather than memorizing an answer per question. Useful ones: solving a problem where the first approach failed, learning something unfamiliar under time pressure, working with someone you disagreed with, and handling a mistake you made. For each, know the situation in a sentence, what you personally did, what happened, and what you would do differently. The same example can answer several different questions if you know it well, which is why depth beats breadth here. This is general editorial preparation advice; the employer's own instructions determine the actual format."],
    ["Explain one project from end to end", "Expect to talk through something you have built, analyzed, or researched. Be ready with the purpose, the constraints, the approach you chose and what you rejected, and how you knew it worked. Separate your contribution from your teammates' clearly and without diminishing either. Practice the explanation on someone outside your field first, then add technical depth when asked — being able to adjust the level is itself a signal. Name a limitation honestly; a candidate who says what their project does not handle is more credible than one who claims everything worked."],
    ["Study the actual team's work", "Read the posting and the official team or program pages, and arrive with a specific reason this work interests you. 'I admire the company' is not a reason; 'the role involves X and I spent last semester on Y' is. Prepare for the format the employer described: for a technical or case assessment, use the preparation material they supply and any practice resources they permit. Do not seek leaked questions or unauthorized help — it usually breaches the terms you agree to and can end your candidacy."],
    ["Ask questions that help you decide", "You are also evaluating them. Useful questions: what an intern actually worked on last cycle, who provides supervision and how often, how feedback is given, what the team is trying to accomplish this year, and what the working schedule really looks like. Save compensation, location, travel, and enrollment conditions for the recruiter rather than the technical interviewer, and resolve them before accepting anything. Do not assume an internship carries a return offer; if that matters to you, ask directly how often it happens."],
    ["Check the practical details beforehand", "Confirm the time and time zone, the meeting link or the address, who you are meeting, and anything you were asked to bring or prepare. For a remote interview, test the platform, camera, microphone, and connection on the actual device you will use, and have a fallback — a phone number or a second network — in case something fails. Ask in advance if you need an accommodation. Arrive a few minutes early and treat everyone you meet as part of the process, because they are."],
    ["Close it out and learn from it", "Write down what you were asked and anything you learned about the role while it is fresh; it is the best preparation for the next round and for other interviews. A brief thank-you note is optional unless the employer says otherwise, and it should be short and specific rather than a second pitch. Then carry on with your other applications while you wait. If you are turned down, you can ask politely whether feedback is available — many employers cannot give it at internship volume, and that is not a reflection on your application."],
  ] },
  { slug: "how-to-follow-up-on-an-internship-email", title: "How to Follow Up on an Internship Application", description: "Check the official application status, respect employer timelines, and send a concise follow-up only through an appropriate contact route.", intro: "A follow-up should clarify a next step, not create pressure. The employer portal and any timeline you were given are the starting points.", sections: [
    ["Check before you send anything", "Most follow-up emails are answered by information the applicant already has. Look for a confirmation message, a status in the employer's portal, an assessment request, or a published decision timeline in the original posting. Check your spam and promotions folders, since automated recruiting mail lands there routinely. If the posting or the employer's careers FAQ says not to contact recruiters directly, or gives a specific support form, follow that instruction — it is part of the process, not a formality. Silence is not a rejection, and it is not an invitation to escalate."],
    ["Wait long enough to be worth answering", "If the employer gave a decision date, wait for it. If it gave none, a reasonable gap after applying is usually a few weeks rather than a few days, and longer around the busiest points of a recruiting cycle or a university term. A message sent too early signals that you did not read the process; one sent after a stated date has passed is entirely reasonable. Send one, and if it goes unanswered, let the next move be theirs."],
    ["Use the right contact, once", "Reply to the recruiter already handling your application, or use the applicant-support route the employer publishes. Do not look up individual employees' addresses, guess an address format, or send the same question to several people at the organization — it is easy to spot and it reliably works against you. Include the role title and its identifier so whoever opens the message can find your application without asking you for it."],
    ["Keep the note short and specific", "State when you applied, confirm you are still interested, and ask one clear question — usually whether there is a next step you should complete. Four sentences is enough. For example: 'I applied for [role and ID] on [date]. I remain interested in the opportunity and wanted to check whether any additional information is needed from me. Thank you for your time.' Replace the brackets with accurate details only. Do not attach your resume again unless it was asked for, and do not use the message to add new claims about your experience."],
    ["Accept the answer, including no answer", "If you are given a date, wait for it before asking again. If you get no response at all, treat that as information and put your effort into other applications rather than a sequence of increasingly urgent messages — the sequence is remembered, and not usefully. Keep your own record of what you sent and when. The employer's portal, not your inbox, remains the authoritative source for where your application stands."],
  ] },
  { slug: "do-internships-pay", title: "How to Compare Internship Pay and Costs", description: "Compare internship salary or stipends with housing, travel, schedule, and the employer's written terms before accepting.", intro: "‘Paid’ is a starting point, not a complete offer. An hourly salary, weekly stipend, and monthly research award can have very different practical implications.", sections: [
    ["Confirm the written amount and schedule", "Read the individual posting and the written offer for the amount, the payment cadence, the expected hours, the exact dates, and any conditions attached. A program overview often describes compensation in general terms without listing a figure for the role you would actually hold, and a range shown for a whole program is not a commitment to you. Distinguish an hourly wage from a weekly stipend and from a one-off research award: they behave differently when the term runs short, when you work extra hours, or when a holiday falls inside the placement. This directory never converts an unknown figure into an estimated salary."],
    ["Work out what the term actually costs you", "Build a simple budget before comparing offers: rent for the full term plus any deposit, travel to and from the site, daily transport, food, and anything you must buy to start. Then set the pay against it. A well-paid placement in an expensive city can leave you with less than a modest one you can do from home, and a deposit due in May is a real problem even when the total works out over the summer. Ask when the first payment actually arrives — a monthly cycle can mean several weeks of costs before any money does."],
    ["Ask how support is delivered, not just whether it exists", "Housing assistance, travel support, and relocation allowances vary enormously in how they reach you. Provided directly, reimbursed after you submit receipts, paid as a lump sum in the first month, or available only to participants meeting separate conditions are four different things, and only the first helps with money you need upfront. Ask specifically what is covered, what evidence is required, and when it is paid. A reimbursement you receive in August does not pay a deposit in May."],
    ["Check the academic and practical conditions", "Confirm whether you need insurance, school approval, or a particular enrollment status to participate, and whether taking academic credit for the internship carries tuition or fees at your institution — credit is sometimes the more expensive option. Ask whether unpaid overtime is expected, what happens if the term dates shift, and what the arrangement is if you need to leave early for the academic year. Questions about wage law, tax treatment, or immigration rules need current official information and, where it matters, qualified advice; this guide is neither legal nor tax advice."],
    ["Separate an advertised program from your actual offer", "A published stipend is useful context for deciding where to apply. It is not what you are being offered until it appears in writing for your role, with your dates and your hours. Before accepting, get the terms in writing and read them. Weigh the parts that are hard to price as well: what you would actually work on, who would supervise you, whether you would learn something you want, and whether the schedule leaves room for the rest of your life. And never pay a service that offers to submit applications on your behalf."],
  ] },
  { slug: "how-to-find-internships", title: "How to Build a Realistic College Internship Shortlist", description: "Find college internships by eligibility, work interests, dates, and location, then save and prioritize applications you can actually complete.", intro: "A shortlist should reduce wasted effort. Begin with eligibility and practical constraints, then compare the work—not just the employer's name.", sections: [
    ["Write down your non-negotiables first", "Before opening a single listing, record your college year, expected graduation month and year, completed credits, the weeks you are actually free, where you can live and work, and your work-authorization situation. These are the filters that remove options fastest, and applying them first saves far more time than applying them after you have written a cover letter. Check mandatory employer rules directly on the official page rather than from a summary. If a program does not state its year requirement, mark it unresolved rather than counting it as a match: an unstated minimum is a question to answer, not a green light."],
    ["Search more than one channel", "Most students search one job board and conclude the market is small. It is not — it is fragmented. Use official employer career pages, your campus career center and its employer relationships, faculty and departmental research opportunities, professional associations in your field, and established program directories. Ask a professor whose class you enjoyed whether their lab takes undergraduates; that conversation surfaces roles that are never posted publicly. FirstInternships helps you interpret selected pathways in depth, but it does not claim to list every available internship, and neither does any single source."],
    ["Compare the work, not the logo", "A recognizable employer name tells you very little about what you would spend the summer doing. For each option, write one sentence on the actual work and one on why it fits something you have already done or genuinely want to learn. If you cannot write either sentence, you do not know enough about the role to write a convincing application for it. This is also the step where a smaller organization often wins: the work is frequently broader, the supervision closer, and the applicant pool smaller."],
    ["Score the effort each application costs", "Applications are not equal in cost. A single-form submission takes twenty minutes; one requiring two essays, a portfolio, and two recommendation letters can take a week of calendar time because other people are involved. Note those dependencies next to each option before committing. Then prioritize deliberately: a few complete, specific applications generally do more for you than a long list submitted thinly, and a deadline you miss because you overcommitted costs you the option entirely."],
    ["Keep a record you will actually use", "Save the official URL, the role identifier, the deadline with its time zone, and a copy of the description — postings are edited and taken down, and you will want the original when preparing for an interview. Use this site's saved list to track planning stages and your next action for each program. That list lives in your own browser on this device, so export it if you want a backup or a copy somewhere else."],
    ["Revisit the list on a schedule", "A shortlist made in September is out of date by November: some cycles will have opened, some closed, and your own interests will have moved. Put a recurring half-hour in your calendar to re-check official pages for the programs you are waiting on, add anything new, and remove what no longer fits. Treating the shortlist as a living document rather than a one-time exercise is what stops a deadline passing unnoticed while you were busy with coursework."],
  ] },
];

export const programPath = program => `/programs/${program.id}`;
export const yearPath = year => `/${year.slug}`;
export const fieldPath = field => `/internships/${field.id}`;
export const guidePath = guide => `/guides/${guide.slug}`;
export const topicPath = topic => `/${topic.slug}`;
export function programsForTopic(topic) { return topic.filter === "paid" ? PROGRAMS.filter(p => p.pay === "Paid") : topic.programIds.map(id => PROGRAMS.find(p => p.id === id)).filter(Boolean); }
export function guidesForProgram(program) {
  const slugs = program.guideSlugs || (program.fields.includes("research") ? ["research-internship-personal-statement", "ask-for-internship-recommendation-letter", "when-to-apply-for-summer-internships"] : ["how-to-apply-for-an-internship", "internship-resume-with-no-experience", "internship-interview-guide"]);
  return slugs.map(slug => GUIDES.find(g => g.slug === slug)).filter(Boolean);
}
export function relatedPrograms(program, limit = 3) {
  const score = candidate => candidate.fields.filter(field => program.fields.includes(field)).length + (candidate.fields.includes(program.fields[0]) ? 2 : 0);
  return PROGRAMS.filter(candidate => candidate.id !== program.id && candidate.fields.some(field => program.fields.includes(field)))
    .sort((a, b) => score(b) - score(a) || a.company.localeCompare(b.company)).slice(0, limit);
}
export function programsForYear(year) { return PROGRAMS.filter(p => p.years.includes(year)); }
export function programsForField(field) { return PROGRAMS.filter(p => p.fields.includes(field)); }
export const ROUTES = ["/", "/internships", ...YEARS.map(yearPath), ...FIELDS.map(fieldPath), ...PROGRAMS.map(programPath), ...TOPICS.map(topicPath), "/guides", ...GUIDES.map(guidePath), "/internship-deadlines", "/application-timeline", "/compare", "/about", "/contact", "/saved", "/404"];
export function normalizePath(path) { return path.replace(/\.html$/, "").replace(/\/$/, "") || "/"; }
export function resolvePage(pathname) {
  const path = normalizePath(pathname);
  const program = PROGRAMS.find(p => programPath(p) === path);
  if (program) return { type: "program", path, program, title: program.seoTitle, description: program.seoDescription };
  const year = YEARS.find(y => yearPath(y) === path);
  if (year) return { type: "year", path, year, title: year.title, description: year.description };
  const field = FIELDS.find(f => fieldPath(f) === path);
  if (field) return { type: "field", path, field, title: field.title, description: field.description };
  const guide = GUIDES.find(g => guidePath(g) === path);
  if (guide) return { type: "guide", path, guide, title: guide.title, description: guide.description };
  const topic = TOPICS.find(t => topicPath(t) === path);
  if (topic) return { type: "topic", path, topic, title: topic.title, description: topic.description };
  const basic = {
    "/": ["home", "College Internships by Class Year", "College internship pathways with sourced eligibility, application guides, and a free personal application tracker. First-year students through seniors."],
    "/internships": ["directory", "College Internship Directory", "Browse sourced undergraduate internship pathways by college year and field. Check eligibility, learn how to apply, and visit the official employer."],
    "/guides": ["guides", "College Internship Application Guides", "College internship playbooks for resumes, cover letters, research statements, recommendation requests, portfolios, interviews, timelines, and offer decisions."],
    "/internship-deadlines": ["deadlines", "College Internship Deadlines & Application Calendar", "Published college internship deadlines for NASA, DOE and NIH, with term, time zone, eligibility links, and a downloadable application-cutoff calendar."],
    "/application-timeline": ["timeline", "College Internship Application Timeline Builder", "Build a personal college internship preparation timeline, plan references and documents, and download a checklist or all-day calendar. Free; no account needed."],
    "/compare": ["compare", "Compare College Internship Program Requirements", "Compare up to three college internship pathways side by side: class-year guidance, eligibility, pay, location, deadlines, and application preparation."],
    "/about": ["about", "About FirstInternships & Our Editorial Process", "How FirstInternships verifies college internship pathways, handles eligibility, updates sources, and keeps advertising separate from editorial decisions."],
    "/contact": ["contact", "Contact FirstInternships", "Report a program correction, suggest an undergraduate opportunity, or contact the FirstInternships directory team."],
    "/saved": ["saved", "Your Saved Internships & Application Tracker", "Plan your internship applications, record next actions, and export your saved list. Stored in your browser, with no account required."],
  }[path];
  return basic ? { type: basic[0], path, title: basic[1], description: basic[2] } : { type: "404", path, title: "Page Not Found", description: "Find college internship pathways and application guides on FirstInternships." };
}

export function searchPrograms({ query = "", year = "all", field = "all", paid = false, ids = null }) {
  const words = query.trim().toLowerCase().split(/\s+/).filter(Boolean);
  // Preferred-year guidance is a useful lead, but remains in the unknown-minimum
  // group with its qualification caveat rather than becoming a hard eligibility rule.
  return PROGRAMS.filter(p => year === "all" || p.years.includes(Number(year)) || p.preferredYears?.includes(Number(year)))
    .filter(p => field === "all" || p.fields.includes(field))
    .filter(p => !paid || p.pay === "Paid")
    .filter(p => !ids || ids.includes(p.id))
    .filter(p => words.every(word => `${p.company} ${p.title} ${p.summary} ${p.location} ${p.fields.map(id => FIELDS.find(f => f.id === id)?.name || id).join(" ")} ${p.eligibility.join(" ")}`.toLowerCase().includes(word)))
    .sort((a, b) => (a.firstYear ?? 99) - (b.firstYear ?? 99) || a.company.localeCompare(b.company));
}
