// Editorial standards and contact guidance. Written 2026-09-20.
//
// These are the site's trust pages. They describe how the directory actually
// works — sourcing, class-year semantics, corrections, funding, and limits — so
// a reader can judge how much weight to give a program page.
//
// Nothing here may promise a response time, a response rate, an outcome, market
// coverage, or a team credential. State what the process is, and state plainly
// what the directory does not do.

export const ABOUT_SECTIONS = [
  ["what-this-is", "What this directory is", "FirstInternships is an independent guide to selected internship pathways open to students who are currently enrolled in an undergraduate degree. Each program has its own page explaining who the publisher says can apply, what the application involves, and what to prepare before starting one. It is free, it requires no account, and applications happen on the employer's or institution's own site. We are not an employer, a recruiter, a staffing firm, or a representative of any organization listed here, and no organization pays to appear."],
  ["how-we-source", "How program facts are sourced", "Eligibility, compensation, dates, work arrangements, and application routes come from first-party sources: the official program page, the current official listing, a government announcement, or the program's own application FAQ. Every program page links the specific sources used and shows the date we reviewed them. We paraphrase rather than copy employer marketing text, and we attribute facts through those links so you can check them yourself. Where a source is ambiguous, we describe the ambiguity instead of resolving it in the employer's favor or ours."],
  ["unknowns", "What happens when a source does not say", "The most common failure in an internship directory is inventing the missing detail. If a publisher does not state a minimum college year, we record that it is unknown rather than assuming all four years qualify. If an announcement gives a date but no time, we do not invent a midnight cutoff or a time zone. If pay is described for a past cohort, we label it as a past award rather than a future guarantee. A page that says a requirement is unclear is more useful than a confident page that turns out to be wrong after you have spent an evening on the application."],
  ["class-years", "How college years are decided", "Programs built specifically for first- and second-year students are labeled that way, and that label is not a floor: a program designed for early-college students does not automatically accept juniors and seniors. Where a publisher describes a graduation window, a penultimate year, or a completed-credit requirement instead of a class year, we keep the publisher's framing rather than converting it into a class-year rule that would not survive contact with an accelerated, transfer, or extended degree. Treat a year match on this site as a starting point, then check the individual opening for credits, enrollment, authorization, and dates."],
  ["editorial-advice", "What is our advice, and what is the employer's requirement", "Every program page separates two things. Sourced facts describe what the publisher requires. Preparation guidance is original editorial advice written by us, and it is marked as such. We have no access to selection decisions, interview questions, or scoring, and we do not claim a relationship with any employer. Our advice can help you understand what an application is asking for and assemble honest evidence; it cannot tell you what a particular reviewer will think, and no guide on this site should be read as a promise of an interview or an offer."],
  ["closed-programs", "Why closed programs stay on the site", "A program whose last cycle has ended is often still worth reading months before the next one opens, because the requirements, materials, and selection process are usually stable even when the dates are not. We keep those pages, and we label them honestly: a closed cycle is shown as closed, and a recurring timeline is described as a recruiting pattern rather than evidence that an application is open. We never roll last year's deadline forward into a guess at this year's. If a page says a cycle has passed, the useful next step is to prepare now and watch the official page for the new announcement."],
  ["not-a-feed", "What this directory is not", "This is a curated set of pathways, not a live vacancies feed, and it does not attempt to list every internship. A program appearing here is not a statement that it is currently accepting applications, and a program missing from here is not a statement that it does not exist or is not worth applying to. Use it alongside your campus career center, faculty and departmental research opportunities, and the employers' own search pages. We do not submit applications, host resumes, forward your details to employers, offer referrals, or sell a service that claims to improve your chances."],
  ["corrections", "Corrections", "Program details change between recruiting cycles, and a page that was accurate at its review date can go out of date without us noticing. If you find something wrong, send the page address and the official source showing the correct information, and we will check it against the publisher and update the page and its review date. Corrections are free and do not require an account. We would rather hear about a broken detail than have a student plan around it, and a correction backed by an official link is the fastest thing for us to act on."],
  ["funding", "How the site is funded, and what that does not buy", "The directory is free to use and we intend to fund it with clearly labeled display advertising. Advertising is currently switched off and will stay off until the required publisher approval and consent configuration are in place. When it is enabled, ad slots will be labeled as advertising and kept visually distinct from program listings, so an advertisement is never mistaken for a recommendation or an application link. Advertising revenue does not affect which programs appear, how they are described, what eligibility we record, or the order they are shown in. No program here is a paid placement, and we do not currently have an affiliate relationship with any listed organization."],
  ["privacy-summary", "What we ask you for", "Nothing. There is no account, no newsletter signup, no resume upload, and no application form on this site. The planner keeps your saved programs, notes, stages, and checklist state in your own browser's local storage, where we cannot read it — it is never sent to a server, never put in a link you share, and never included in an analytics event. Contact messages open a draft in your own email app rather than submitting through a form here. The full detail is in the privacy policy."],
];

export const ABOUT_FAQS = [
  ["Does a program appearing here mean it is open right now?", "No. Each page shows the program's status at the date we reviewed its sources, and availability can change immediately afterward. The employer's official page is always the authoritative answer on whether an application is currently open."],
  ["Can you tell me whether I am eligible?", "We cannot. We can explain what a publisher's stated requirements appear to mean and which details are worth checking, but only the employer can decide an individual case — and for questions about enrollment or work authorization, your own institution's advisers are the right place to start."],
  ["Do you get paid when I apply to a program?", "No. There is no affiliate, referral, or paid-placement arrangement behind any program on this site. We plan to fund the directory with labeled display advertising, which is separate from the editorial content and does not influence it."],
  ["Why is a well-known employer's internship missing?", "Usually because we have not reviewed it against official sources yet, not because we judged it unsuitable. Coverage grows as programs are researched. You are welcome to suggest one through the contact page with its official link."],
  ["How current is the information?", "Every program page carries the date its sources were last reviewed. Treat anything older than your current recruiting cycle as a starting point to re-check rather than a settled fact, and always confirm dates on the official page before you plan around them."],
];

export const CONTACT_TOPICS = [
  ["Program correction", "Include the address of our page, the detail that is wrong, and a link to the official source showing the correct information. Corrections with an official link are the fastest for us to verify and act on."],
  ["Suggest a college internship", "Include the official employer or institution link, who is eligible by college year or graduation window, the term and location, and any published compensation. Programs open to currently enrolled undergraduates are in scope; graduate, high-school, and full-time roles are not."],
  ["Advertising inquiry", "Advertising is not yet live on the site. You are welcome to get in touch, but we cannot confirm placements, rates, or availability at this stage, and we do not sell placement within program listings or influence over editorial content."],
  ["Privacy or general question", "Because there is no account and the planner stores everything in your own browser, we usually hold no data about you to look up. If you have emailed us before, you can ask what we still have from that exchange and request that we delete it."],
];

export const CONTACT_LIMITS = [
  "We cannot check, forward, expedite, or ask about the status of your application — the employer's own portal is the only authoritative source for that.",
  "We cannot refer you to an employer, pass on a resume, or introduce you to a recruiter.",
  "We cannot decide whether you personally meet a program's eligibility rules, or advise on immigration, tax, or employment law.",
  "We do not want resumes, transcripts, identification documents, or account passwords, and we ask that you do not send them.",
];
